"""empty message

Revision ID: 385105ddb063
Revises: 2fe43a6c0096
Create Date: 2019-10-24 16:16:27.935176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385105ddb063'
down_revision = '2fe43a6c0096'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_task',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=256), nullable=True),
    sa.Column('commit_id', sa.String(length=256), nullable=True, comment='This is a unique ID that represents a database commit. In the case of calendar sync, the commits are done on a cal by cal basis and therefore the commit ID should be the Calendar ID'),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('pull_start', sa.DateTime(), nullable=True, comment='A timestamp of when pulling data for a commit started'),
    sa.Column('pull_end', sa.DateTime(), nullable=True, comment='A timestamp of when pulling data for a commit ended'),
    sa.Column('store_start', sa.DateTime(), nullable=True, comment='A timestamp of storing data for a commit started'),
    sa.Column('store_end', sa.DateTime(), nullable=True, comment='A timestamp of storing data for a commit ended'),
    sa.ForeignKeyConstraint(['sync_id'], ['sync.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_task')
    op.drop_table('sync')
    # ### end Alembic commands ###


def upgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

