"""empty message

Revision ID: 5e634fc119ae
Revises: 3368ac633bb4
Create Date: 2019-10-09 21:52:05.255230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e634fc119ae'
down_revision = '3368ac633bb4'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_databases', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_databases', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_databases', 'time_updated')
    op.drop_column('user_databases', 'time_created')
    op.drop_column('user', 'time_updated')
    op.drop_column('user', 'time_created')
    # ### end Alembic commands ###


def upgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_attendees')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('calendar_id', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('organizer_email', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('is_recurring', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('start_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('end_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=5000), nullable=True),
    sa.CheckConstraint('(`is_recurring` in (0,1))', name='events_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('event_attendees',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('working_hours_start_time', mysql.TIME(), nullable=True),
    sa.Column('working_hours_end_time', mysql.TIME(), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('response_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_organizer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_optional', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`is_optional` in (0,1))', name='event_attendees_chk_2'),
    sa.CheckConstraint('(`is_organizer` in (0,1))', name='event_attendees_chk_1'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_attendees_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###

