"""empty message

Revision ID: 7f38d1967c45
Revises: 5e634fc119ae
Create Date: 2019-10-09 22:00:10.759334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f38d1967c45'
down_revision = '5e634fc119ae'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('calendar_id', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('organizer_email', sa.String(length=200), nullable=True),
    sa.Column('is_recurring', sa.BOOLEAN(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_event_attendees',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('working_hours_start_time', sa.TIME(), nullable=True),
    sa.Column('working_hours_end_time', sa.TIME(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('response_status', sa.String(length=20), nullable=True),
    sa.Column('is_organizer', sa.BOOLEAN(), nullable=True),
    sa.Column('is_optional', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_event_attendees')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###

