"""empty message

Revision ID: a86e8ae7409e
Revises: 5e8c4ef09023
Create Date: 2019-10-15 13:06:07.787804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a86e8ae7409e'
down_revision = '5e8c4ef09023'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_user',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('primary_alias', sa.String(length=200), nullable=True),
    sa.Column('given_name', sa.String(length=200), nullable=True),
    sa.Column('family_name', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('current_calendar_timezone', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_user_alias',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('calendar_user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['calendar_user_id'], ['calendar_user.id'], ),
    sa.PrimaryKeyConstraint('alias')
    )
    op.add_column('calendar_event_attendees', sa.Column('calendar_user_id', sa.String(length=100), nullable=True))
    op.add_column('calendar_event_attendees', sa.Column('comment', sa.String(length=5000), nullable=True))
    op.add_column('calendar_event_attendees', sa.Column('invited_email', sa.String(length=200), nullable=True))
    op.add_column('calendar_event_attendees', sa.Column('timezone_organized', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'calendar_event_attendees', 'calendar_user', ['calendar_user_id'], ['id'])
    op.drop_column('calendar_event_attendees', 'email')
    op.add_column('calendar_events', sa.Column('creator_email', sa.String(length=200), nullable=True))
    op.add_column('calendar_events', sa.Column('status', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'status')
    op.drop_column('calendar_events', 'creator_email')
    op.add_column('calendar_event_attendees', sa.Column('email', mysql.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'calendar_event_attendees', type_='foreignkey')
    op.drop_column('calendar_event_attendees', 'timezone_organized')
    op.drop_column('calendar_event_attendees', 'invited_email')
    op.drop_column('calendar_event_attendees', 'comment')
    op.drop_column('calendar_event_attendees', 'calendar_user_id')
    op.drop_table('calendar_user_alias')
    op.drop_table('calendar_user')
    # ### end Alembic commands ###

