"""empty message

Revision ID: ff9e3d5d3b1f
Revises: dd43bb045fec
Create Date: 2019-10-22 19:11:56.605095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9e3d5d3b1f'
down_revision = 'dd43bb045fec'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('family_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('given_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('picture_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture_url')
    op.drop_column('user', 'name')
    op.drop_column('user', 'given_name')
    op.drop_column('user', 'family_name')
    # ### end Alembic commands ###


def upgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_user_db():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

